import fs from 'fs';
import path from 'path';
import OshaToolClient from './OshaToolClient';

// Match the rest of the site: canonical host is www.masterenglishbook.com
// (this is what the sitemap and the GSC property use). Hardcoding the
// bare-domain here made this the only page emitting a non-www canonical,
// a conflicting signal that kept Google from indexing it.
const siteURL = process.env.NEXT_PUBLIC_WEBSITE_URL || 'https://www.masterenglishbook.com';
const pageURL = `${siteURL}/international/osha-safety-tool`;

export const metadata = {
  title: 'OSHA Safety Briefing & Sign-In Sheet Generator - Free PDF',
  description: 'Instantly create compliant OSHA safety briefing notes & crew sign-in sheets. Select hazard topics, customize, and download a printable 1-page PDF. Built for US/UK site managers.',
  keywords: 'OSHA safety briefing, sign-in sheet, daily toolbox talk, construction safety, safety forms, OSHA compliance',
  alternates: {
    canonical: pageURL,
  },
  openGraph: {
    title: 'Free OSHA Safety Briefing & Sign-In Sheet Generator',
    description: 'Instant OSHA-compliant safety briefing forms. Download as PDF, print, and share with your crew.',
    type: 'website',
    url: pageURL,
    // Image auto-generated by opengraph-image.js in this route segment
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Free OSHA Safety Briefing & Sign-In Sheet Generator',
    description: 'Create compliant OSHA safety briefing forms in 30 seconds. Free PDF download.',
    // Image auto-generated by opengraph-image.js in this route segment
  },
};

export default function OSHAToolPage() {
  // Read the HTML file
  const htmlPath = path.join(process.cwd(), 'public', 'osha-safety-tool.html');
  let htmlContent = '';

  try {
    htmlContent = fs.readFileSync(htmlPath, 'utf-8');
  } catch (error) {
    console.error('Error reading OSHA tool file:', error);
    return <div>Error loading OSHA tool. Please refresh the page.</div>;
  }

  return <OshaToolClient htmlContent={htmlContent} />;
}
